### ISSUE TITLE
Running code does not work (`saveTemporaryTerritory`)

### ISSUE THREAD

**Issue by complanar** [cgloeckner/blockly-kara#2]
The function `saveTemporaryTerritory()` is no longer available (as of f92fe09). This introduces an error (see browser development console) in `scripts/staticScripts/controls.js:20`.

**Comment by cgloeckner** [comment]
We probably don't need to save the territory before executing, because it's never loaded from it. Hence running a program alters the world without resetting it automatically (which is probably intended behavior).

Hence [b5955a7](https://github.com/cgloeckner/blockly-kara/commit/b5955a77374f99a148beaad59508231a83363182) should fix it by removing the call to the non-existing function.

**Comment by complanar** [comment]
I'm not sure about this. `scripts/staticScripts/controls.js:92` loads a "temporary territory" when the execution of the code is  stopped, rather than paused.

I think, the intended behaviour should be this:

- At the beginning of code execution save the current territory (controls.js:20)
- While the code is executed, it alters the territory
- When the code is stopped the territory is reset to the state it had before code execution (controls.js:92)

In my opinion it is just the name of the function that is misleading. There is no "temporary territory" that is saved somewhere, but the initial territory is saved temporarily so it can be reset after code execution.

**Comment by complanar** [comment]
Fixed with 7e0219e4af6d1e36f524a0cbcf0794fe85535d92.
